# Generated by Django 6.0.1 on 2026-01-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_access_token",
            field=models.TextField(
                blank=True, help_text="Google OAuth access token", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_refresh_token",
            field=models.TextField(
                blank=True, help_text="Google OAuth refresh token", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_token_expiry",
            field=models.DateTimeField(
                blank=True, help_text="Access token expiry time", null=True
            ),
        ),
    ]
