# Generated by Django 6.0.1 on 2026-01-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0002_user_google_access_token_user_google_refresh_token_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="docs_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="drive_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="gmail_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="sheets_connected",
            field=models.BooleanField(default=False),
        ),
    ]
